# Generated by Django 4.2.3 on 2023-07-26 06:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreInfo",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="StoreTimezoneData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone_str",
                    models.CharField(default="America/Chicago", max_length=255),
                ),
                (
                    "store_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="STD_store_id",
                        to="ReportApp.storeinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreStatusInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_utc", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "store_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SSI_store_id",
                        to="ReportApp.storeinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreBusinessHourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(6)],
                    ),
                ),
                ("start_time_local", models.TimeField(blank=True, null=True)),
                ("end_time_local", models.TimeField(blank=True, null=True)),
                (
                    "store_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SBH_store_id",
                        to="ReportApp.storeinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportData",
            fields=[
                (
                    "report_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("uptime_last_hour", models.PositiveIntegerField(null=True)),
                ("uptime_last_day", models.PositiveIntegerField(null=True)),
                ("uptime_last_week", models.PositiveIntegerField(null=True)),
                ("downtime_last_hour", models.PositiveIntegerField(null=True)),
                ("downtime_last_day", models.PositiveIntegerField(null=True)),
                ("downtime_last_week", models.PositiveIntegerField(null=True)),
                (
                    "store_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="RD_store_id",
                        to="ReportApp.storeinfo",
                    ),
                ),
            ],
        ),
    ]
